spring.application.name=mes

# Dados de Conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/mes
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor=org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor


spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/mes/protocol/openid-connect/certs


logging.level.org.springframework.security=TRACE